server:
  port: 8080

spring:
  application:
    name: MCS-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          httpserver:
            wiretap: true
          httpclient:
            wiretap: true
          routes:
            - id: user-fm
              uri: lb://MCS-USER-FM
              predicates:
                - Path=/api/funnyMind/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true


