server:
  port: 8080

spring:
  application:
    name: MCS-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          httpserver:
            wiretap: true
          httpclient:
            wiretap: true
            connect-timeout: 5000
            response-timeout: 10s
          routes:
            - id: user-fm
              uri: lb://MCS-USER-FM
              predicates:
                - Path=/pipejfdv/api/v1/funnyMind/**
              filters:
                - StripPrefix=3
            - id: auth-service
              uri: lb://MCS-AUTH
              predicates:
                - Path=/pipejfdv/api/v1/auth/**
              filters:
                - StripPrefix=3
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${jwt.secret}

logging:
  level:
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true


