server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  profiles:
    active: native
  application:
    name: MCS-CONFIG
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  # Configuración para leer variables de entorno
  config:
    import: optional:classpath:.env